model_type: dp_clip
dataset_path: InternRobotics/InternData-BridgeV2
num_gpus: 1
batch_size: 16
output_dir: Checkpoints/runs/gr00t_n1_google_bridgedata_v2
max_steps: 10000
tune_visual: True
tune_llm: False
save_steps: 1000
data_config: bridgedata_v2
video_backend: decord
report_to: wandb
gradient_accumulation_steps: 8
